/**
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "SlasconeOpenApiClient/model/AnalyticalFieldFilterDto.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

AnalyticalFieldFilterDto::AnalyticalFieldFilterDto()
{
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
}

AnalyticalFieldFilterDto::~AnalyticalFieldFilterDto()
{
}

void AnalyticalFieldFilterDto::validate()
{
    // TODO: implement validation
}

web::json::value AnalyticalFieldFilterDto::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_Values.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("values"))] = ModelBase::toJson(m_Values.get());
    }

    return val;
}

bool AnalyticalFieldFilterDto::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("values"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("values")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setValues;
            ok &= ModelBase::fromJson(fieldValue, refVal_setValues);
            setValues(refVal_setValues);
            
        }
    }
    return ok;
}

void AnalyticalFieldFilterDto::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_Values.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("values")), m_Values.get()));
    }
}

bool AnalyticalFieldFilterDto::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("values"))))
    {
        std::vector<utility::string_t> refVal_setValues;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("values"))), refVal_setValues );
        setValues(refVal_setValues);
    }
    return ok;
}


utility::string_t AnalyticalFieldFilterDto::getId() const
{
    return m_Id;
}


void AnalyticalFieldFilterDto::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool AnalyticalFieldFilterDto::idIsSet() const
{
    return m_IdIsSet;
}

void AnalyticalFieldFilterDto::unsetId()
{
    m_IdIsSet = false;
}
std::vector<utility::string_t> AnalyticalFieldFilterDto::getValues() const
{
    return m_Values.get();
}


void AnalyticalFieldFilterDto::setValues(const std::vector<utility::string_t>& value)
{
    m_Values = value;
}

bool AnalyticalFieldFilterDto::valuesIsSet() const
{
    return m_Values.has_value();
}

void AnalyticalFieldFilterDto::unsetValues()
{
    m_Values.reset();
}

}
}
}
}


