/**
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "SlasconeOpenApiClient/model/ConsumptionDto.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

ConsumptionDto::ConsumptionDto()
{
    m_Limitation_id = utility::conversions::to_string_t("");
    m_Limitation_idIsSet = false;
    m_Limit = 0.0;
    m_LimitIsSet = false;
    m_Last_reset_date_utc = utility::datetime();
    m_Last_reset_date_utcIsSet = false;
}

ConsumptionDto::~ConsumptionDto()
{
}

void ConsumptionDto::validate()
{
    // TODO: implement validation
}

web::json::value ConsumptionDto::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Transaction_id.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("transaction_id"))] = ModelBase::toJson(m_Transaction_id.get());
    }
    if(m_Limitation_idIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("limitation_id"))] = ModelBase::toJson(m_Limitation_id);
    }
    if(m_Remaining.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("remaining"))] = ModelBase::toJson(m_Remaining.get());
    }
    if(m_Balance.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("balance"))] = ModelBase::toJson(m_Balance.get());
    }
    if(m_LimitIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("limit"))] = ModelBase::toJson(m_Limit);
    }
    if(m_Goodwill.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("goodwill"))] = ModelBase::toJson(m_Goodwill.get());
    }
    if(m_Last_reset_date_utcIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("last_reset_date_utc"))] = ModelBase::toJson(m_Last_reset_date_utc);
    }
    if(m_Next_reset_date_utc.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("next_reset_date_utc"))] = ModelBase::toJson(m_Next_reset_date_utc.get());
    }

    return val;
}

bool ConsumptionDto::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("transaction_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("transaction_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTransactionId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTransactionId);
            setTransactionId(refVal_setTransactionId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("limitation_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("limitation_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLimitationId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLimitationId);
            setLimitationId(refVal_setLimitationId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("remaining"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("remaining")));
        if(!fieldValue.is_null())
        {
            double refVal_setRemaining;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRemaining);
            setRemaining(refVal_setRemaining);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("balance"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("balance")));
        if(!fieldValue.is_null())
        {
            double refVal_setBalance;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBalance);
            setBalance(refVal_setBalance);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("limit"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("limit")));
        if(!fieldValue.is_null())
        {
            double refVal_setLimit;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLimit);
            setLimit(refVal_setLimit);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("goodwill"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("goodwill")));
        if(!fieldValue.is_null())
        {
            double refVal_setGoodwill;
            ok &= ModelBase::fromJson(fieldValue, refVal_setGoodwill);
            setGoodwill(refVal_setGoodwill);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("last_reset_date_utc"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("last_reset_date_utc")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setLastResetDateUtc;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLastResetDateUtc);
            setLastResetDateUtc(refVal_setLastResetDateUtc);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("next_reset_date_utc"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("next_reset_date_utc")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setNextResetDateUtc;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNextResetDateUtc);
            setNextResetDateUtc(refVal_setNextResetDateUtc);
            
        }
    }
    return ok;
}

void ConsumptionDto::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Transaction_id.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("transaction_id")), m_Transaction_id.get()));
    }
    if(m_Limitation_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("limitation_id")), m_Limitation_id));
    }
    if(m_Remaining.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("remaining")), m_Remaining.get()));
    }
    if(m_Balance.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("balance")), m_Balance.get()));
    }
    if(m_LimitIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("limit")), m_Limit));
    }
    if(m_Goodwill.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("goodwill")), m_Goodwill.get()));
    }
    if(m_Last_reset_date_utcIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("last_reset_date_utc")), m_Last_reset_date_utc));
    }
    if(m_Next_reset_date_utc.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("next_reset_date_utc")), m_Next_reset_date_utc.get()));
    }
}

bool ConsumptionDto::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("transaction_id"))))
    {
        utility::string_t refVal_setTransactionId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("transaction_id"))), refVal_setTransactionId );
        setTransactionId(refVal_setTransactionId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("limitation_id"))))
    {
        utility::string_t refVal_setLimitationId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("limitation_id"))), refVal_setLimitationId );
        setLimitationId(refVal_setLimitationId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("remaining"))))
    {
        double refVal_setRemaining;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("remaining"))), refVal_setRemaining );
        setRemaining(refVal_setRemaining);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("balance"))))
    {
        double refVal_setBalance;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("balance"))), refVal_setBalance );
        setBalance(refVal_setBalance);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("limit"))))
    {
        double refVal_setLimit;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("limit"))), refVal_setLimit );
        setLimit(refVal_setLimit);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("goodwill"))))
    {
        double refVal_setGoodwill;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("goodwill"))), refVal_setGoodwill );
        setGoodwill(refVal_setGoodwill);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("last_reset_date_utc"))))
    {
        utility::datetime refVal_setLastResetDateUtc;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("last_reset_date_utc"))), refVal_setLastResetDateUtc );
        setLastResetDateUtc(refVal_setLastResetDateUtc);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("next_reset_date_utc"))))
    {
        utility::datetime refVal_setNextResetDateUtc;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("next_reset_date_utc"))), refVal_setNextResetDateUtc );
        setNextResetDateUtc(refVal_setNextResetDateUtc);
    }
    return ok;
}


utility::string_t ConsumptionDto::getTransactionId() const
{
    return m_Transaction_id.get();
}


void ConsumptionDto::setTransactionId(const utility::string_t& value)
{
    m_Transaction_id = value;
}

bool ConsumptionDto::transactionIdIsSet() const
{
    return m_Transaction_id.has_value();
}

void ConsumptionDto::unsetTransaction_id()
{
    m_Transaction_id.reset();
}
utility::string_t ConsumptionDto::getLimitationId() const
{
    return m_Limitation_id;
}


void ConsumptionDto::setLimitationId(const utility::string_t& value)
{
    m_Limitation_id = value;
    m_Limitation_idIsSet = true;
}

bool ConsumptionDto::limitationIdIsSet() const
{
    return m_Limitation_idIsSet;
}

void ConsumptionDto::unsetLimitation_id()
{
    m_Limitation_idIsSet = false;
}
double ConsumptionDto::getRemaining() const
{
    return m_Remaining.get();
}

void ConsumptionDto::setRemaining(double value)
{
    m_Remaining = value;
}

bool ConsumptionDto::remainingIsSet() const
{
    return m_Remaining.has_value();
}

void ConsumptionDto::unsetRemaining()
{
    m_Remaining.reset();
}
double ConsumptionDto::getBalance() const
{
    return m_Balance.get();
}

void ConsumptionDto::setBalance(double value)
{
    m_Balance = value;
}

bool ConsumptionDto::balanceIsSet() const
{
    return m_Balance.has_value();
}

void ConsumptionDto::unsetBalance()
{
    m_Balance.reset();
}
double ConsumptionDto::getLimit() const
{
    return m_Limit;
}

void ConsumptionDto::setLimit(double value)
{
    m_Limit = value;
    m_LimitIsSet = true;
}

bool ConsumptionDto::limitIsSet() const
{
    return m_LimitIsSet;
}

void ConsumptionDto::unsetLimit()
{
    m_LimitIsSet = false;
}
double ConsumptionDto::getGoodwill() const
{
    return m_Goodwill.get();
}

void ConsumptionDto::setGoodwill(double value)
{
    m_Goodwill = value;
}

bool ConsumptionDto::goodwillIsSet() const
{
    return m_Goodwill.has_value();
}

void ConsumptionDto::unsetGoodwill()
{
    m_Goodwill.reset();
}
utility::datetime ConsumptionDto::getLastResetDateUtc() const
{
    return m_Last_reset_date_utc;
}


void ConsumptionDto::setLastResetDateUtc(const utility::datetime& value)
{
    m_Last_reset_date_utc = value;
    m_Last_reset_date_utcIsSet = true;
}

bool ConsumptionDto::lastResetDateUtcIsSet() const
{
    return m_Last_reset_date_utcIsSet;
}

void ConsumptionDto::unsetLast_reset_date_utc()
{
    m_Last_reset_date_utcIsSet = false;
}
utility::datetime ConsumptionDto::getNextResetDateUtc() const
{
    return m_Next_reset_date_utc.get();
}


void ConsumptionDto::setNextResetDateUtc(const utility::datetime& value)
{
    m_Next_reset_date_utc = value;
}

bool ConsumptionDto::nextResetDateUtcIsSet() const
{
    return m_Next_reset_date_utc.has_value();
}

void ConsumptionDto::unsetNext_reset_date_utc()
{
    m_Next_reset_date_utc.reset();
}

}
}
}
}


