/**
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "SlasconeOpenApiClient/model/CustomListDto.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

CustomListDto::CustomListDto()
{
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
}

CustomListDto::~CustomListDto()
{
}

void CustomListDto::validate()
{
    // TODO: implement validation
}

web::json::value CustomListDto::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_Custom_list_name.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("custom_list_name"))] = ModelBase::toJson(m_Custom_list_name.get());
    }
    if(m_Elements.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("elements"))] = ModelBase::toJson(m_Elements.get());
    }
    if(m_Created_date_utc.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("created_date_utc"))] = ModelBase::toJson(m_Created_date_utc.get());
    }
    if(m_Modified_date_utc.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("modified_date_utc"))] = ModelBase::toJson(m_Modified_date_utc.get());
    }
    if(m_Last_modified_by.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("last_modified_by"))] = ModelBase::toJson(m_Last_modified_by.get());
    }

    return val;
}

bool CustomListDto::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("custom_list_name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("custom_list_name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCustomListName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCustomListName);
            setCustomListName(refVal_setCustomListName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("elements"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("elements")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<CustomListElementDto>> refVal_setElements;
            ok &= ModelBase::fromJson(fieldValue, refVal_setElements);
            setElements(refVal_setElements);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("created_date_utc"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("created_date_utc")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setCreatedDateUtc;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedDateUtc);
            setCreatedDateUtc(refVal_setCreatedDateUtc);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("modified_date_utc"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("modified_date_utc")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setModifiedDateUtc;
            ok &= ModelBase::fromJson(fieldValue, refVal_setModifiedDateUtc);
            setModifiedDateUtc(refVal_setModifiedDateUtc);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("last_modified_by"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("last_modified_by")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLastModifiedBy;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLastModifiedBy);
            setLastModifiedBy(refVal_setLastModifiedBy);
            
        }
    }
    return ok;
}

void CustomListDto::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_Custom_list_name.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("custom_list_name")), m_Custom_list_name.get()));
    }
    if(m_Elements.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("elements")), m_Elements.get()));
    }
    if(m_Created_date_utc.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("created_date_utc")), m_Created_date_utc.get()));
    }
    if(m_Modified_date_utc.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("modified_date_utc")), m_Modified_date_utc.get()));
    }
    if(m_Last_modified_by.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("last_modified_by")), m_Last_modified_by.get()));
    }
}

bool CustomListDto::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("custom_list_name"))))
    {
        utility::string_t refVal_setCustomListName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("custom_list_name"))), refVal_setCustomListName );
        setCustomListName(refVal_setCustomListName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("elements"))))
    {
        std::vector<std::shared_ptr<CustomListElementDto>> refVal_setElements;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("elements"))), refVal_setElements );
        setElements(refVal_setElements);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("created_date_utc"))))
    {
        utility::datetime refVal_setCreatedDateUtc;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("created_date_utc"))), refVal_setCreatedDateUtc );
        setCreatedDateUtc(refVal_setCreatedDateUtc);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("modified_date_utc"))))
    {
        utility::datetime refVal_setModifiedDateUtc;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("modified_date_utc"))), refVal_setModifiedDateUtc );
        setModifiedDateUtc(refVal_setModifiedDateUtc);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("last_modified_by"))))
    {
        utility::string_t refVal_setLastModifiedBy;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("last_modified_by"))), refVal_setLastModifiedBy );
        setLastModifiedBy(refVal_setLastModifiedBy);
    }
    return ok;
}


utility::string_t CustomListDto::getId() const
{
    return m_Id;
}


void CustomListDto::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool CustomListDto::idIsSet() const
{
    return m_IdIsSet;
}

void CustomListDto::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t CustomListDto::getCustomListName() const
{
    return m_Custom_list_name.get();
}


void CustomListDto::setCustomListName(const utility::string_t& value)
{
    m_Custom_list_name = value;
}

bool CustomListDto::customListNameIsSet() const
{
    return m_Custom_list_name.has_value();
}

void CustomListDto::unsetCustom_list_name()
{
    m_Custom_list_name.reset();
}
std::vector<std::shared_ptr<CustomListElementDto>> CustomListDto::getElements() const
{
    return m_Elements.get();
}


void CustomListDto::setElements(const std::vector<std::shared_ptr<CustomListElementDto>>& value)
{
    m_Elements = value;
}

bool CustomListDto::elementsIsSet() const
{
    return m_Elements.has_value();
}

void CustomListDto::unsetElements()
{
    m_Elements.reset();
}
utility::datetime CustomListDto::getCreatedDateUtc() const
{
    return m_Created_date_utc.get();
}


void CustomListDto::setCreatedDateUtc(const utility::datetime& value)
{
    m_Created_date_utc = value;
}

bool CustomListDto::createdDateUtcIsSet() const
{
    return m_Created_date_utc.has_value();
}

void CustomListDto::unsetCreated_date_utc()
{
    m_Created_date_utc.reset();
}
utility::datetime CustomListDto::getModifiedDateUtc() const
{
    return m_Modified_date_utc.get();
}


void CustomListDto::setModifiedDateUtc(const utility::datetime& value)
{
    m_Modified_date_utc = value;
}

bool CustomListDto::modifiedDateUtcIsSet() const
{
    return m_Modified_date_utc.has_value();
}

void CustomListDto::unsetModified_date_utc()
{
    m_Modified_date_utc.reset();
}
utility::string_t CustomListDto::getLastModifiedBy() const
{
    return m_Last_modified_by.get();
}


void CustomListDto::setLastModifiedBy(const utility::string_t& value)
{
    m_Last_modified_by = value;
}

bool CustomListDto::lastModifiedByIsSet() const
{
    return m_Last_modified_by.has_value();
}

void CustomListDto::unsetLast_modified_by()
{
    m_Last_modified_by.reset();
}

}
}
}
}


