/**
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "SlasconeOpenApiClient/model/CustomerDto.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

CustomerDto::CustomerDto()
{
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_Customer_typeIsSet = false;
    m_LogoIsSet = false;
}

CustomerDto::~CustomerDto()
{
}

void CustomerDto::validate()
{
    // TODO: implement validation
}

web::json::value CustomerDto::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_Company_name.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("company_name"))] = ModelBase::toJson(m_Company_name.get());
    }
    if(m_Customer_number.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("customer_number"))] = ModelBase::toJson(m_Customer_number.get());
    }
    if(m_Customer_typeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("customer_type"))] = ModelBase::toJson(m_Customer_type);
    }
    if(m_Email.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("email"))] = ModelBase::toJson(m_Email.get());
    }
    if(m_Street.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("street"))] = ModelBase::toJson(m_Street.get());
    }
    if(m_City.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("city"))] = ModelBase::toJson(m_City.get());
    }
    if(m_Postalcode.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("postalcode"))] = ModelBase::toJson(m_Postalcode.get());
    }
    if(m_Country.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("country"))] = ModelBase::toJson(m_Country.get());
    }
    if(m_Phone.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("phone"))] = ModelBase::toJson(m_Phone.get());
    }
    if(m_Prospect_number.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("prospect_number"))] = ModelBase::toJson(m_Prospect_number.get());
    }
    if(m_Longitude.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("longitude"))] = ModelBase::toJson(m_Longitude.get());
    }
    if(m_Latitude.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("latitude"))] = ModelBase::toJson(m_Latitude.get());
    }
    if(m_Created_date_utc.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("created_date_utc"))] = ModelBase::toJson(m_Created_date_utc.get());
    }
    if(m_Modified_date_utc.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("modified_date_utc"))] = ModelBase::toJson(m_Modified_date_utc.get());
    }
    if(m_Last_modified_by.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("last_modified_by"))] = ModelBase::toJson(m_Last_modified_by.get());
    }
    if(m_Tag_assignments.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tag_assignments"))] = ModelBase::toJson(m_Tag_assignments.get());
    }
    if(m_LogoIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("logo"))] = ModelBase::toJson(m_Logo);
    }
    if(m_Reseller_id.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("reseller_id"))] = ModelBase::toJson(m_Reseller_id.get());
    }

    return val;
}

bool CustomerDto::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("company_name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("company_name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCompanyName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCompanyName);
            setCompanyName(refVal_setCompanyName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("customer_number"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("customer_number")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCustomerNumber;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCustomerNumber);
            setCustomerNumber(refVal_setCustomerNumber);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("customer_type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("customer_type")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<CustomerTypeDto> refVal_setCustomerType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCustomerType);
            setCustomerType(refVal_setCustomerType);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("email"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("email")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEmail;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEmail);
            setEmail(refVal_setEmail);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("street"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("street")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStreet;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStreet);
            setStreet(refVal_setStreet);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("city"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("city")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCity;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCity);
            setCity(refVal_setCity);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("postalcode"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("postalcode")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPostalcode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPostalcode);
            setPostalcode(refVal_setPostalcode);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("country"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("country")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCountry;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCountry);
            setCountry(refVal_setCountry);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("phone"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("phone")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPhone;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPhone);
            setPhone(refVal_setPhone);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("prospect_number"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("prospect_number")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setProspectNumber;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProspectNumber);
            setProspectNumber(refVal_setProspectNumber);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("longitude"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("longitude")));
        if(!fieldValue.is_null())
        {
            double refVal_setLongitude;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLongitude);
            setLongitude(refVal_setLongitude);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("latitude"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("latitude")));
        if(!fieldValue.is_null())
        {
            double refVal_setLatitude;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLatitude);
            setLatitude(refVal_setLatitude);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("created_date_utc"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("created_date_utc")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setCreatedDateUtc;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedDateUtc);
            setCreatedDateUtc(refVal_setCreatedDateUtc);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("modified_date_utc"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("modified_date_utc")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setModifiedDateUtc;
            ok &= ModelBase::fromJson(fieldValue, refVal_setModifiedDateUtc);
            setModifiedDateUtc(refVal_setModifiedDateUtc);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("last_modified_by"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("last_modified_by")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLastModifiedBy;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLastModifiedBy);
            setLastModifiedBy(refVal_setLastModifiedBy);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tag_assignments"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tag_assignments")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<TagAssignmentDto>> refVal_setTagAssignments;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTagAssignments);
            setTagAssignments(refVal_setTagAssignments);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("logo"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("logo")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<ResourceDto> refVal_setLogo;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLogo);
            setLogo(refVal_setLogo);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("reseller_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("reseller_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setResellerId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setResellerId);
            setResellerId(refVal_setResellerId);
            
        }
    }
    return ok;
}

void CustomerDto::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_Company_name.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("company_name")), m_Company_name.get()));
    }
    if(m_Customer_number.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("customer_number")), m_Customer_number.get()));
    }
    if(m_Customer_typeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("customer_type")), m_Customer_type));
    }
    if(m_Email.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("email")), m_Email.get()));
    }
    if(m_Street.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("street")), m_Street.get()));
    }
    if(m_City.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("city")), m_City.get()));
    }
    if(m_Postalcode.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("postalcode")), m_Postalcode.get()));
    }
    if(m_Country.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("country")), m_Country.get()));
    }
    if(m_Phone.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("phone")), m_Phone.get()));
    }
    if(m_Prospect_number.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("prospect_number")), m_Prospect_number.get()));
    }
    if(m_Longitude.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("longitude")), m_Longitude.get()));
    }
    if(m_Latitude.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("latitude")), m_Latitude.get()));
    }
    if(m_Created_date_utc.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("created_date_utc")), m_Created_date_utc.get()));
    }
    if(m_Modified_date_utc.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("modified_date_utc")), m_Modified_date_utc.get()));
    }
    if(m_Last_modified_by.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("last_modified_by")), m_Last_modified_by.get()));
    }
    if(m_Tag_assignments.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tag_assignments")), m_Tag_assignments.get()));
    }
    if(m_LogoIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("logo")), m_Logo));
    }
    if(m_Reseller_id.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("reseller_id")), m_Reseller_id.get()));
    }
}

bool CustomerDto::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("company_name"))))
    {
        utility::string_t refVal_setCompanyName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("company_name"))), refVal_setCompanyName );
        setCompanyName(refVal_setCompanyName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("customer_number"))))
    {
        utility::string_t refVal_setCustomerNumber;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("customer_number"))), refVal_setCustomerNumber );
        setCustomerNumber(refVal_setCustomerNumber);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("customer_type"))))
    {
        std::shared_ptr<CustomerTypeDto> refVal_setCustomerType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("customer_type"))), refVal_setCustomerType );
        setCustomerType(refVal_setCustomerType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("email"))))
    {
        utility::string_t refVal_setEmail;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("email"))), refVal_setEmail );
        setEmail(refVal_setEmail);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("street"))))
    {
        utility::string_t refVal_setStreet;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("street"))), refVal_setStreet );
        setStreet(refVal_setStreet);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("city"))))
    {
        utility::string_t refVal_setCity;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("city"))), refVal_setCity );
        setCity(refVal_setCity);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("postalcode"))))
    {
        utility::string_t refVal_setPostalcode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("postalcode"))), refVal_setPostalcode );
        setPostalcode(refVal_setPostalcode);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("country"))))
    {
        utility::string_t refVal_setCountry;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("country"))), refVal_setCountry );
        setCountry(refVal_setCountry);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("phone"))))
    {
        utility::string_t refVal_setPhone;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("phone"))), refVal_setPhone );
        setPhone(refVal_setPhone);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("prospect_number"))))
    {
        utility::string_t refVal_setProspectNumber;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("prospect_number"))), refVal_setProspectNumber );
        setProspectNumber(refVal_setProspectNumber);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("longitude"))))
    {
        double refVal_setLongitude;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("longitude"))), refVal_setLongitude );
        setLongitude(refVal_setLongitude);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("latitude"))))
    {
        double refVal_setLatitude;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("latitude"))), refVal_setLatitude );
        setLatitude(refVal_setLatitude);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("created_date_utc"))))
    {
        utility::datetime refVal_setCreatedDateUtc;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("created_date_utc"))), refVal_setCreatedDateUtc );
        setCreatedDateUtc(refVal_setCreatedDateUtc);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("modified_date_utc"))))
    {
        utility::datetime refVal_setModifiedDateUtc;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("modified_date_utc"))), refVal_setModifiedDateUtc );
        setModifiedDateUtc(refVal_setModifiedDateUtc);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("last_modified_by"))))
    {
        utility::string_t refVal_setLastModifiedBy;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("last_modified_by"))), refVal_setLastModifiedBy );
        setLastModifiedBy(refVal_setLastModifiedBy);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tag_assignments"))))
    {
        std::vector<std::shared_ptr<TagAssignmentDto>> refVal_setTagAssignments;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tag_assignments"))), refVal_setTagAssignments );
        setTagAssignments(refVal_setTagAssignments);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("logo"))))
    {
        std::shared_ptr<ResourceDto> refVal_setLogo;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("logo"))), refVal_setLogo );
        setLogo(refVal_setLogo);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("reseller_id"))))
    {
        utility::string_t refVal_setResellerId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("reseller_id"))), refVal_setResellerId );
        setResellerId(refVal_setResellerId);
    }
    return ok;
}


utility::string_t CustomerDto::getId() const
{
    return m_Id;
}


void CustomerDto::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool CustomerDto::idIsSet() const
{
    return m_IdIsSet;
}

void CustomerDto::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t CustomerDto::getCompanyName() const
{
    return m_Company_name.get();
}


void CustomerDto::setCompanyName(const utility::string_t& value)
{
    m_Company_name = value;
}

bool CustomerDto::companyNameIsSet() const
{
    return m_Company_name.has_value();
}

void CustomerDto::unsetCompany_name()
{
    m_Company_name.reset();
}
utility::string_t CustomerDto::getCustomerNumber() const
{
    return m_Customer_number.get();
}


void CustomerDto::setCustomerNumber(const utility::string_t& value)
{
    m_Customer_number = value;
}

bool CustomerDto::customerNumberIsSet() const
{
    return m_Customer_number.has_value();
}

void CustomerDto::unsetCustomer_number()
{
    m_Customer_number.reset();
}
std::shared_ptr<CustomerTypeDto> CustomerDto::getCustomerType() const
{
    return m_Customer_type;
}


void CustomerDto::setCustomerType(const std::shared_ptr<CustomerTypeDto>& value)
{
    m_Customer_type = value;
    m_Customer_typeIsSet = true;
}

bool CustomerDto::customerTypeIsSet() const
{
    return m_Customer_typeIsSet;
}

void CustomerDto::unsetCustomer_type()
{
    m_Customer_typeIsSet = false;
}
utility::string_t CustomerDto::getEmail() const
{
    return m_Email.get();
}


void CustomerDto::setEmail(const utility::string_t& value)
{
    m_Email = value;
}

bool CustomerDto::emailIsSet() const
{
    return m_Email.has_value();
}

void CustomerDto::unsetEmail()
{
    m_Email.reset();
}
utility::string_t CustomerDto::getStreet() const
{
    return m_Street.get();
}


void CustomerDto::setStreet(const utility::string_t& value)
{
    m_Street = value;
}

bool CustomerDto::streetIsSet() const
{
    return m_Street.has_value();
}

void CustomerDto::unsetStreet()
{
    m_Street.reset();
}
utility::string_t CustomerDto::getCity() const
{
    return m_City.get();
}


void CustomerDto::setCity(const utility::string_t& value)
{
    m_City = value;
}

bool CustomerDto::cityIsSet() const
{
    return m_City.has_value();
}

void CustomerDto::unsetCity()
{
    m_City.reset();
}
utility::string_t CustomerDto::getPostalcode() const
{
    return m_Postalcode.get();
}


void CustomerDto::setPostalcode(const utility::string_t& value)
{
    m_Postalcode = value;
}

bool CustomerDto::postalcodeIsSet() const
{
    return m_Postalcode.has_value();
}

void CustomerDto::unsetPostalcode()
{
    m_Postalcode.reset();
}
utility::string_t CustomerDto::getCountry() const
{
    return m_Country.get();
}


void CustomerDto::setCountry(const utility::string_t& value)
{
    m_Country = value;
}

bool CustomerDto::countryIsSet() const
{
    return m_Country.has_value();
}

void CustomerDto::unsetCountry()
{
    m_Country.reset();
}
utility::string_t CustomerDto::getPhone() const
{
    return m_Phone.get();
}


void CustomerDto::setPhone(const utility::string_t& value)
{
    m_Phone = value;
}

bool CustomerDto::phoneIsSet() const
{
    return m_Phone.has_value();
}

void CustomerDto::unsetPhone()
{
    m_Phone.reset();
}
utility::string_t CustomerDto::getProspectNumber() const
{
    return m_Prospect_number.get();
}


void CustomerDto::setProspectNumber(const utility::string_t& value)
{
    m_Prospect_number = value;
}

bool CustomerDto::prospectNumberIsSet() const
{
    return m_Prospect_number.has_value();
}

void CustomerDto::unsetProspect_number()
{
    m_Prospect_number.reset();
}
double CustomerDto::getLongitude() const
{
    return m_Longitude.get();
}

void CustomerDto::setLongitude(double value)
{
    m_Longitude = value;
}

bool CustomerDto::longitudeIsSet() const
{
    return m_Longitude.has_value();
}

void CustomerDto::unsetLongitude()
{
    m_Longitude.reset();
}
double CustomerDto::getLatitude() const
{
    return m_Latitude.get();
}

void CustomerDto::setLatitude(double value)
{
    m_Latitude = value;
}

bool CustomerDto::latitudeIsSet() const
{
    return m_Latitude.has_value();
}

void CustomerDto::unsetLatitude()
{
    m_Latitude.reset();
}
utility::datetime CustomerDto::getCreatedDateUtc() const
{
    return m_Created_date_utc.get();
}


void CustomerDto::setCreatedDateUtc(const utility::datetime& value)
{
    m_Created_date_utc = value;
}

bool CustomerDto::createdDateUtcIsSet() const
{
    return m_Created_date_utc.has_value();
}

void CustomerDto::unsetCreated_date_utc()
{
    m_Created_date_utc.reset();
}
utility::datetime CustomerDto::getModifiedDateUtc() const
{
    return m_Modified_date_utc.get();
}


void CustomerDto::setModifiedDateUtc(const utility::datetime& value)
{
    m_Modified_date_utc = value;
}

bool CustomerDto::modifiedDateUtcIsSet() const
{
    return m_Modified_date_utc.has_value();
}

void CustomerDto::unsetModified_date_utc()
{
    m_Modified_date_utc.reset();
}
utility::string_t CustomerDto::getLastModifiedBy() const
{
    return m_Last_modified_by.get();
}


void CustomerDto::setLastModifiedBy(const utility::string_t& value)
{
    m_Last_modified_by = value;
}

bool CustomerDto::lastModifiedByIsSet() const
{
    return m_Last_modified_by.has_value();
}

void CustomerDto::unsetLast_modified_by()
{
    m_Last_modified_by.reset();
}
std::vector<std::shared_ptr<TagAssignmentDto>> CustomerDto::getTagAssignments() const
{
    return m_Tag_assignments.get();
}


void CustomerDto::setTagAssignments(const std::vector<std::shared_ptr<TagAssignmentDto>>& value)
{
    m_Tag_assignments = value;
}

bool CustomerDto::tagAssignmentsIsSet() const
{
    return m_Tag_assignments.has_value();
}

void CustomerDto::unsetTag_assignments()
{
    m_Tag_assignments.reset();
}
std::shared_ptr<ResourceDto> CustomerDto::getLogo() const
{
    return m_Logo;
}


void CustomerDto::setLogo(const std::shared_ptr<ResourceDto>& value)
{
    m_Logo = value;
    m_LogoIsSet = true;
}

bool CustomerDto::logoIsSet() const
{
    return m_LogoIsSet;
}

void CustomerDto::unsetLogo()
{
    m_LogoIsSet = false;
}
utility::string_t CustomerDto::getResellerId() const
{
    return m_Reseller_id.get();
}


void CustomerDto::setResellerId(const utility::string_t& value)
{
    m_Reseller_id = value;
}

bool CustomerDto::resellerIdIsSet() const
{
    return m_Reseller_id.has_value();
}

void CustomerDto::unsetReseller_id()
{
    m_Reseller_id.reset();
}

}
}
}
}


