/**
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "SlasconeOpenApiClient/model/DataExchangeAddCustomerDto.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

DataExchangeAddCustomerDto::DataExchangeAddCustomerDto()
{
    m_Customer_number = utility::conversions::to_string_t("");
    m_Customer_numberIsSet = false;
    m_Customer_name = utility::conversions::to_string_t("");
    m_Customer_nameIsSet = false;
    m_Customer_type = utility::conversions::to_string_t("");
    m_Customer_typeIsSet = false;
    m_Country = utility::conversions::to_string_t("");
    m_CountryIsSet = false;
}

DataExchangeAddCustomerDto::~DataExchangeAddCustomerDto()
{
}

void DataExchangeAddCustomerDto::validate()
{
    // TODO: implement validation
}

web::json::value DataExchangeAddCustomerDto::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Customer_numberIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("customer_number"))] = ModelBase::toJson(m_Customer_number);
    }
    if(m_Customer_nameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("customer_name"))] = ModelBase::toJson(m_Customer_name);
    }
    if(m_Customer_typeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("customer_type"))] = ModelBase::toJson(m_Customer_type);
    }
    if(m_CountryIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("country"))] = ModelBase::toJson(m_Country);
    }
    if(m_Street.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("street"))] = ModelBase::toJson(m_Street.get());
    }
    if(m_Zip.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("zip"))] = ModelBase::toJson(m_Zip.get());
    }
    if(m_City.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("city"))] = ModelBase::toJson(m_City.get());
    }
    if(m_Phone.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("phone"))] = ModelBase::toJson(m_Phone.get());
    }
    if(m_Email.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("email"))] = ModelBase::toJson(m_Email.get());
    }
    if(m_Prospect_number.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("prospect_number"))] = ModelBase::toJson(m_Prospect_number.get());
    }
    if(m_Tags.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tags"))] = ModelBase::toJson(m_Tags.get());
    }

    return val;
}

bool DataExchangeAddCustomerDto::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("customer_number"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("customer_number")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCustomerNumber;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCustomerNumber);
            setCustomerNumber(refVal_setCustomerNumber);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("customer_name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("customer_name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCustomerName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCustomerName);
            setCustomerName(refVal_setCustomerName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("customer_type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("customer_type")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCustomerType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCustomerType);
            setCustomerType(refVal_setCustomerType);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("country"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("country")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCountry;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCountry);
            setCountry(refVal_setCountry);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("street"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("street")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStreet;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStreet);
            setStreet(refVal_setStreet);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("zip"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("zip")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setZip;
            ok &= ModelBase::fromJson(fieldValue, refVal_setZip);
            setZip(refVal_setZip);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("city"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("city")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCity;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCity);
            setCity(refVal_setCity);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("phone"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("phone")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPhone;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPhone);
            setPhone(refVal_setPhone);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("email"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("email")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEmail;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEmail);
            setEmail(refVal_setEmail);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("prospect_number"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("prospect_number")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setProspectNumber;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProspectNumber);
            setProspectNumber(refVal_setProspectNumber);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tags"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tags")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setTags;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTags);
            setTags(refVal_setTags);
            
        }
    }
    return ok;
}

void DataExchangeAddCustomerDto::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Customer_numberIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("customer_number")), m_Customer_number));
    }
    if(m_Customer_nameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("customer_name")), m_Customer_name));
    }
    if(m_Customer_typeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("customer_type")), m_Customer_type));
    }
    if(m_CountryIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("country")), m_Country));
    }
    if(m_Street.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("street")), m_Street.get()));
    }
    if(m_Zip.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("zip")), m_Zip.get()));
    }
    if(m_City.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("city")), m_City.get()));
    }
    if(m_Phone.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("phone")), m_Phone.get()));
    }
    if(m_Email.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("email")), m_Email.get()));
    }
    if(m_Prospect_number.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("prospect_number")), m_Prospect_number.get()));
    }
    if(m_Tags.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tags")), m_Tags.get()));
    }
}

bool DataExchangeAddCustomerDto::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("customer_number"))))
    {
        utility::string_t refVal_setCustomerNumber;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("customer_number"))), refVal_setCustomerNumber );
        setCustomerNumber(refVal_setCustomerNumber);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("customer_name"))))
    {
        utility::string_t refVal_setCustomerName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("customer_name"))), refVal_setCustomerName );
        setCustomerName(refVal_setCustomerName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("customer_type"))))
    {
        utility::string_t refVal_setCustomerType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("customer_type"))), refVal_setCustomerType );
        setCustomerType(refVal_setCustomerType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("country"))))
    {
        utility::string_t refVal_setCountry;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("country"))), refVal_setCountry );
        setCountry(refVal_setCountry);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("street"))))
    {
        utility::string_t refVal_setStreet;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("street"))), refVal_setStreet );
        setStreet(refVal_setStreet);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("zip"))))
    {
        utility::string_t refVal_setZip;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("zip"))), refVal_setZip );
        setZip(refVal_setZip);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("city"))))
    {
        utility::string_t refVal_setCity;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("city"))), refVal_setCity );
        setCity(refVal_setCity);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("phone"))))
    {
        utility::string_t refVal_setPhone;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("phone"))), refVal_setPhone );
        setPhone(refVal_setPhone);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("email"))))
    {
        utility::string_t refVal_setEmail;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("email"))), refVal_setEmail );
        setEmail(refVal_setEmail);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("prospect_number"))))
    {
        utility::string_t refVal_setProspectNumber;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("prospect_number"))), refVal_setProspectNumber );
        setProspectNumber(refVal_setProspectNumber);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tags"))))
    {
        std::vector<utility::string_t> refVal_setTags;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tags"))), refVal_setTags );
        setTags(refVal_setTags);
    }
    return ok;
}


utility::string_t DataExchangeAddCustomerDto::getCustomerNumber() const
{
    return m_Customer_number;
}


void DataExchangeAddCustomerDto::setCustomerNumber(const utility::string_t& value)
{
    m_Customer_number = value;
    m_Customer_numberIsSet = true;
}

bool DataExchangeAddCustomerDto::customerNumberIsSet() const
{
    return m_Customer_numberIsSet;
}

void DataExchangeAddCustomerDto::unsetCustomer_number()
{
    m_Customer_numberIsSet = false;
}
utility::string_t DataExchangeAddCustomerDto::getCustomerName() const
{
    return m_Customer_name;
}


void DataExchangeAddCustomerDto::setCustomerName(const utility::string_t& value)
{
    m_Customer_name = value;
    m_Customer_nameIsSet = true;
}

bool DataExchangeAddCustomerDto::customerNameIsSet() const
{
    return m_Customer_nameIsSet;
}

void DataExchangeAddCustomerDto::unsetCustomer_name()
{
    m_Customer_nameIsSet = false;
}
utility::string_t DataExchangeAddCustomerDto::getCustomerType() const
{
    return m_Customer_type;
}


void DataExchangeAddCustomerDto::setCustomerType(const utility::string_t& value)
{
    m_Customer_type = value;
    m_Customer_typeIsSet = true;
}

bool DataExchangeAddCustomerDto::customerTypeIsSet() const
{
    return m_Customer_typeIsSet;
}

void DataExchangeAddCustomerDto::unsetCustomer_type()
{
    m_Customer_typeIsSet = false;
}
utility::string_t DataExchangeAddCustomerDto::getCountry() const
{
    return m_Country;
}


void DataExchangeAddCustomerDto::setCountry(const utility::string_t& value)
{
    m_Country = value;
    m_CountryIsSet = true;
}

bool DataExchangeAddCustomerDto::countryIsSet() const
{
    return m_CountryIsSet;
}

void DataExchangeAddCustomerDto::unsetCountry()
{
    m_CountryIsSet = false;
}
utility::string_t DataExchangeAddCustomerDto::getStreet() const
{
    return m_Street.get();
}


void DataExchangeAddCustomerDto::setStreet(const utility::string_t& value)
{
    m_Street = value;
}

bool DataExchangeAddCustomerDto::streetIsSet() const
{
    return m_Street.has_value();
}

void DataExchangeAddCustomerDto::unsetStreet()
{
    m_Street.reset();
}
utility::string_t DataExchangeAddCustomerDto::getZip() const
{
    return m_Zip.get();
}


void DataExchangeAddCustomerDto::setZip(const utility::string_t& value)
{
    m_Zip = value;
}

bool DataExchangeAddCustomerDto::zipIsSet() const
{
    return m_Zip.has_value();
}

void DataExchangeAddCustomerDto::unsetZip()
{
    m_Zip.reset();
}
utility::string_t DataExchangeAddCustomerDto::getCity() const
{
    return m_City.get();
}


void DataExchangeAddCustomerDto::setCity(const utility::string_t& value)
{
    m_City = value;
}

bool DataExchangeAddCustomerDto::cityIsSet() const
{
    return m_City.has_value();
}

void DataExchangeAddCustomerDto::unsetCity()
{
    m_City.reset();
}
utility::string_t DataExchangeAddCustomerDto::getPhone() const
{
    return m_Phone.get();
}


void DataExchangeAddCustomerDto::setPhone(const utility::string_t& value)
{
    m_Phone = value;
}

bool DataExchangeAddCustomerDto::phoneIsSet() const
{
    return m_Phone.has_value();
}

void DataExchangeAddCustomerDto::unsetPhone()
{
    m_Phone.reset();
}
utility::string_t DataExchangeAddCustomerDto::getEmail() const
{
    return m_Email.get();
}


void DataExchangeAddCustomerDto::setEmail(const utility::string_t& value)
{
    m_Email = value;
}

bool DataExchangeAddCustomerDto::emailIsSet() const
{
    return m_Email.has_value();
}

void DataExchangeAddCustomerDto::unsetEmail()
{
    m_Email.reset();
}
utility::string_t DataExchangeAddCustomerDto::getProspectNumber() const
{
    return m_Prospect_number.get();
}


void DataExchangeAddCustomerDto::setProspectNumber(const utility::string_t& value)
{
    m_Prospect_number = value;
}

bool DataExchangeAddCustomerDto::prospectNumberIsSet() const
{
    return m_Prospect_number.has_value();
}

void DataExchangeAddCustomerDto::unsetProspect_number()
{
    m_Prospect_number.reset();
}
std::vector<utility::string_t> DataExchangeAddCustomerDto::getTags() const
{
    return m_Tags.get();
}


void DataExchangeAddCustomerDto::setTags(const std::vector<utility::string_t>& value)
{
    m_Tags = value;
}

bool DataExchangeAddCustomerDto::tagsIsSet() const
{
    return m_Tags.has_value();
}

void DataExchangeAddCustomerDto::unsetTags()
{
    m_Tags.reset();
}

}
}
}
}


