/**
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "SlasconeOpenApiClient/model/DeviceHeartbeatDto.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

DeviceHeartbeatDto::DeviceHeartbeatDto()
{
    m_Created_date_utc = utility::datetime();
    m_Created_date_utcIsSet = false;
    m_Device_license_assignment_id = utility::conversions::to_string_t("");
    m_Device_license_assignment_idIsSet = false;
    m_Device_license_id = utility::conversions::to_string_t("");
    m_Device_license_idIsSet = false;
    m_Heartbeat_typeIsSet = false;
    m_License_userIsSet = false;
    m_Value = 0;
    m_ValueIsSet = false;
}

DeviceHeartbeatDto::~DeviceHeartbeatDto()
{
}

void DeviceHeartbeatDto::validate()
{
    // TODO: implement validation
}

web::json::value DeviceHeartbeatDto::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Id.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id.get());
    }
    if(m_Software_version.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("software_version"))] = ModelBase::toJson(m_Software_version.get());
    }
    if(m_Operating_system.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("operating_system"))] = ModelBase::toJson(m_Operating_system.get());
    }
    if(m_Ip_address.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("ip_address"))] = ModelBase::toJson(m_Ip_address.get());
    }
    if(m_Client_id.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("client_id"))] = ModelBase::toJson(m_Client_id.get());
    }
    if(m_Country.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("country"))] = ModelBase::toJson(m_Country.get());
    }
    if(m_City.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("city"))] = ModelBase::toJson(m_City.get());
    }
    if(m_Zip.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("zip"))] = ModelBase::toJson(m_Zip.get());
    }
    if(m_Latitude.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("latitude"))] = ModelBase::toJson(m_Latitude.get());
    }
    if(m_Longitude.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("longitude"))] = ModelBase::toJson(m_Longitude.get());
    }
    if(m_Created_date_utcIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("created_date_utc"))] = ModelBase::toJson(m_Created_date_utc);
    }
    if(m_Device_license_assignment_idIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("device_license_assignment_id"))] = ModelBase::toJson(m_Device_license_assignment_id);
    }
    if(m_Device_license_idIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("device_license_id"))] = ModelBase::toJson(m_Device_license_id);
    }
    if(m_Customer_name.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("customer_name"))] = ModelBase::toJson(m_Customer_name.get());
    }
    if(m_Heartbeat_type_id.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("heartbeat_type_id"))] = ModelBase::toJson(m_Heartbeat_type_id.get());
    }
    if(m_Heartbeat_typeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("heartbeat_type"))] = ModelBase::toJson(m_Heartbeat_type);
    }
    if(m_User_id.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("user_id"))] = ModelBase::toJson(m_User_id.get());
    }
    if(m_License_userIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("license_user"))] = ModelBase::toJson(m_License_user);
    }
    if(m_Group_id.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("group_id"))] = ModelBase::toJson(m_Group_id.get());
    }
    if(m_ValueIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("value"))] = ModelBase::toJson(m_Value);
    }

    return val;
}

bool DeviceHeartbeatDto::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("software_version"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("software_version")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSoftwareVersion;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSoftwareVersion);
            setSoftwareVersion(refVal_setSoftwareVersion);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("operating_system"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("operating_system")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setOperatingSystem;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOperatingSystem);
            setOperatingSystem(refVal_setOperatingSystem);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("ip_address"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("ip_address")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setIpAddress;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIpAddress);
            setIpAddress(refVal_setIpAddress);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("client_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("client_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setClientId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setClientId);
            setClientId(refVal_setClientId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("country"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("country")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCountry;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCountry);
            setCountry(refVal_setCountry);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("city"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("city")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCity;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCity);
            setCity(refVal_setCity);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("zip"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("zip")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setZip;
            ok &= ModelBase::fromJson(fieldValue, refVal_setZip);
            setZip(refVal_setZip);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("latitude"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("latitude")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLatitude;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLatitude);
            setLatitude(refVal_setLatitude);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("longitude"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("longitude")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLongitude;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLongitude);
            setLongitude(refVal_setLongitude);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("created_date_utc"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("created_date_utc")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setCreatedDateUtc;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedDateUtc);
            setCreatedDateUtc(refVal_setCreatedDateUtc);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("device_license_assignment_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("device_license_assignment_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDeviceLicenseAssignmentId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDeviceLicenseAssignmentId);
            setDeviceLicenseAssignmentId(refVal_setDeviceLicenseAssignmentId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("device_license_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("device_license_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDeviceLicenseId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDeviceLicenseId);
            setDeviceLicenseId(refVal_setDeviceLicenseId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("customer_name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("customer_name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCustomerName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCustomerName);
            setCustomerName(refVal_setCustomerName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("heartbeat_type_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("heartbeat_type_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setHeartbeatTypeId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setHeartbeatTypeId);
            setHeartbeatTypeId(refVal_setHeartbeatTypeId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("heartbeat_type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("heartbeat_type")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<HeartbeatTypeDto> refVal_setHeartbeatType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setHeartbeatType);
            setHeartbeatType(refVal_setHeartbeatType);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("user_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("user_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUserId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUserId);
            setUserId(refVal_setUserId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("license_user"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("license_user")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<LicenseUserDto> refVal_setLicenseUser;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLicenseUser);
            setLicenseUser(refVal_setLicenseUser);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("group_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("group_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setGroupId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setGroupId);
            setGroupId(refVal_setGroupId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("value"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("value")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setValue;
            ok &= ModelBase::fromJson(fieldValue, refVal_setValue);
            setValue(refVal_setValue);
            
        }
    }
    return ok;
}

void DeviceHeartbeatDto::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Id.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id.get()));
    }
    if(m_Software_version.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("software_version")), m_Software_version.get()));
    }
    if(m_Operating_system.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("operating_system")), m_Operating_system.get()));
    }
    if(m_Ip_address.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("ip_address")), m_Ip_address.get()));
    }
    if(m_Client_id.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("client_id")), m_Client_id.get()));
    }
    if(m_Country.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("country")), m_Country.get()));
    }
    if(m_City.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("city")), m_City.get()));
    }
    if(m_Zip.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("zip")), m_Zip.get()));
    }
    if(m_Latitude.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("latitude")), m_Latitude.get()));
    }
    if(m_Longitude.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("longitude")), m_Longitude.get()));
    }
    if(m_Created_date_utcIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("created_date_utc")), m_Created_date_utc));
    }
    if(m_Device_license_assignment_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("device_license_assignment_id")), m_Device_license_assignment_id));
    }
    if(m_Device_license_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("device_license_id")), m_Device_license_id));
    }
    if(m_Customer_name.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("customer_name")), m_Customer_name.get()));
    }
    if(m_Heartbeat_type_id.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("heartbeat_type_id")), m_Heartbeat_type_id.get()));
    }
    if(m_Heartbeat_typeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("heartbeat_type")), m_Heartbeat_type));
    }
    if(m_User_id.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("user_id")), m_User_id.get()));
    }
    if(m_License_userIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("license_user")), m_License_user));
    }
    if(m_Group_id.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("group_id")), m_Group_id.get()));
    }
    if(m_ValueIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("value")), m_Value));
    }
}

bool DeviceHeartbeatDto::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("software_version"))))
    {
        utility::string_t refVal_setSoftwareVersion;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("software_version"))), refVal_setSoftwareVersion );
        setSoftwareVersion(refVal_setSoftwareVersion);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("operating_system"))))
    {
        utility::string_t refVal_setOperatingSystem;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("operating_system"))), refVal_setOperatingSystem );
        setOperatingSystem(refVal_setOperatingSystem);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("ip_address"))))
    {
        utility::string_t refVal_setIpAddress;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("ip_address"))), refVal_setIpAddress );
        setIpAddress(refVal_setIpAddress);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("client_id"))))
    {
        utility::string_t refVal_setClientId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("client_id"))), refVal_setClientId );
        setClientId(refVal_setClientId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("country"))))
    {
        utility::string_t refVal_setCountry;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("country"))), refVal_setCountry );
        setCountry(refVal_setCountry);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("city"))))
    {
        utility::string_t refVal_setCity;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("city"))), refVal_setCity );
        setCity(refVal_setCity);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("zip"))))
    {
        utility::string_t refVal_setZip;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("zip"))), refVal_setZip );
        setZip(refVal_setZip);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("latitude"))))
    {
        utility::string_t refVal_setLatitude;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("latitude"))), refVal_setLatitude );
        setLatitude(refVal_setLatitude);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("longitude"))))
    {
        utility::string_t refVal_setLongitude;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("longitude"))), refVal_setLongitude );
        setLongitude(refVal_setLongitude);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("created_date_utc"))))
    {
        utility::datetime refVal_setCreatedDateUtc;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("created_date_utc"))), refVal_setCreatedDateUtc );
        setCreatedDateUtc(refVal_setCreatedDateUtc);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("device_license_assignment_id"))))
    {
        utility::string_t refVal_setDeviceLicenseAssignmentId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("device_license_assignment_id"))), refVal_setDeviceLicenseAssignmentId );
        setDeviceLicenseAssignmentId(refVal_setDeviceLicenseAssignmentId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("device_license_id"))))
    {
        utility::string_t refVal_setDeviceLicenseId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("device_license_id"))), refVal_setDeviceLicenseId );
        setDeviceLicenseId(refVal_setDeviceLicenseId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("customer_name"))))
    {
        utility::string_t refVal_setCustomerName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("customer_name"))), refVal_setCustomerName );
        setCustomerName(refVal_setCustomerName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("heartbeat_type_id"))))
    {
        utility::string_t refVal_setHeartbeatTypeId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("heartbeat_type_id"))), refVal_setHeartbeatTypeId );
        setHeartbeatTypeId(refVal_setHeartbeatTypeId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("heartbeat_type"))))
    {
        std::shared_ptr<HeartbeatTypeDto> refVal_setHeartbeatType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("heartbeat_type"))), refVal_setHeartbeatType );
        setHeartbeatType(refVal_setHeartbeatType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("user_id"))))
    {
        utility::string_t refVal_setUserId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("user_id"))), refVal_setUserId );
        setUserId(refVal_setUserId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("license_user"))))
    {
        std::shared_ptr<LicenseUserDto> refVal_setLicenseUser;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("license_user"))), refVal_setLicenseUser );
        setLicenseUser(refVal_setLicenseUser);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("group_id"))))
    {
        utility::string_t refVal_setGroupId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("group_id"))), refVal_setGroupId );
        setGroupId(refVal_setGroupId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("value"))))
    {
        int32_t refVal_setValue;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("value"))), refVal_setValue );
        setValue(refVal_setValue);
    }
    return ok;
}


utility::string_t DeviceHeartbeatDto::getId() const
{
    return m_Id.get();
}


void DeviceHeartbeatDto::setId(const utility::string_t& value)
{
    m_Id = value;
}

bool DeviceHeartbeatDto::idIsSet() const
{
    return m_Id.has_value();
}

void DeviceHeartbeatDto::unsetId()
{
    m_Id.reset();
}
utility::string_t DeviceHeartbeatDto::getSoftwareVersion() const
{
    return m_Software_version.get();
}


void DeviceHeartbeatDto::setSoftwareVersion(const utility::string_t& value)
{
    m_Software_version = value;
}

bool DeviceHeartbeatDto::softwareVersionIsSet() const
{
    return m_Software_version.has_value();
}

void DeviceHeartbeatDto::unsetSoftware_version()
{
    m_Software_version.reset();
}
utility::string_t DeviceHeartbeatDto::getOperatingSystem() const
{
    return m_Operating_system.get();
}


void DeviceHeartbeatDto::setOperatingSystem(const utility::string_t& value)
{
    m_Operating_system = value;
}

bool DeviceHeartbeatDto::operatingSystemIsSet() const
{
    return m_Operating_system.has_value();
}

void DeviceHeartbeatDto::unsetOperating_system()
{
    m_Operating_system.reset();
}
utility::string_t DeviceHeartbeatDto::getIpAddress() const
{
    return m_Ip_address.get();
}


void DeviceHeartbeatDto::setIpAddress(const utility::string_t& value)
{
    m_Ip_address = value;
}

bool DeviceHeartbeatDto::ipAddressIsSet() const
{
    return m_Ip_address.has_value();
}

void DeviceHeartbeatDto::unsetIp_address()
{
    m_Ip_address.reset();
}
utility::string_t DeviceHeartbeatDto::getClientId() const
{
    return m_Client_id.get();
}


void DeviceHeartbeatDto::setClientId(const utility::string_t& value)
{
    m_Client_id = value;
}

bool DeviceHeartbeatDto::clientIdIsSet() const
{
    return m_Client_id.has_value();
}

void DeviceHeartbeatDto::unsetClient_id()
{
    m_Client_id.reset();
}
utility::string_t DeviceHeartbeatDto::getCountry() const
{
    return m_Country.get();
}


void DeviceHeartbeatDto::setCountry(const utility::string_t& value)
{
    m_Country = value;
}

bool DeviceHeartbeatDto::countryIsSet() const
{
    return m_Country.has_value();
}

void DeviceHeartbeatDto::unsetCountry()
{
    m_Country.reset();
}
utility::string_t DeviceHeartbeatDto::getCity() const
{
    return m_City.get();
}


void DeviceHeartbeatDto::setCity(const utility::string_t& value)
{
    m_City = value;
}

bool DeviceHeartbeatDto::cityIsSet() const
{
    return m_City.has_value();
}

void DeviceHeartbeatDto::unsetCity()
{
    m_City.reset();
}
utility::string_t DeviceHeartbeatDto::getZip() const
{
    return m_Zip.get();
}


void DeviceHeartbeatDto::setZip(const utility::string_t& value)
{
    m_Zip = value;
}

bool DeviceHeartbeatDto::zipIsSet() const
{
    return m_Zip.has_value();
}

void DeviceHeartbeatDto::unsetZip()
{
    m_Zip.reset();
}
utility::string_t DeviceHeartbeatDto::getLatitude() const
{
    return m_Latitude.get();
}


void DeviceHeartbeatDto::setLatitude(const utility::string_t& value)
{
    m_Latitude = value;
}

bool DeviceHeartbeatDto::latitudeIsSet() const
{
    return m_Latitude.has_value();
}

void DeviceHeartbeatDto::unsetLatitude()
{
    m_Latitude.reset();
}
utility::string_t DeviceHeartbeatDto::getLongitude() const
{
    return m_Longitude.get();
}


void DeviceHeartbeatDto::setLongitude(const utility::string_t& value)
{
    m_Longitude = value;
}

bool DeviceHeartbeatDto::longitudeIsSet() const
{
    return m_Longitude.has_value();
}

void DeviceHeartbeatDto::unsetLongitude()
{
    m_Longitude.reset();
}
utility::datetime DeviceHeartbeatDto::getCreatedDateUtc() const
{
    return m_Created_date_utc;
}


void DeviceHeartbeatDto::setCreatedDateUtc(const utility::datetime& value)
{
    m_Created_date_utc = value;
    m_Created_date_utcIsSet = true;
}

bool DeviceHeartbeatDto::createdDateUtcIsSet() const
{
    return m_Created_date_utcIsSet;
}

void DeviceHeartbeatDto::unsetCreated_date_utc()
{
    m_Created_date_utcIsSet = false;
}
utility::string_t DeviceHeartbeatDto::getDeviceLicenseAssignmentId() const
{
    return m_Device_license_assignment_id;
}


void DeviceHeartbeatDto::setDeviceLicenseAssignmentId(const utility::string_t& value)
{
    m_Device_license_assignment_id = value;
    m_Device_license_assignment_idIsSet = true;
}

bool DeviceHeartbeatDto::deviceLicenseAssignmentIdIsSet() const
{
    return m_Device_license_assignment_idIsSet;
}

void DeviceHeartbeatDto::unsetDevice_license_assignment_id()
{
    m_Device_license_assignment_idIsSet = false;
}
utility::string_t DeviceHeartbeatDto::getDeviceLicenseId() const
{
    return m_Device_license_id;
}


void DeviceHeartbeatDto::setDeviceLicenseId(const utility::string_t& value)
{
    m_Device_license_id = value;
    m_Device_license_idIsSet = true;
}

bool DeviceHeartbeatDto::deviceLicenseIdIsSet() const
{
    return m_Device_license_idIsSet;
}

void DeviceHeartbeatDto::unsetDevice_license_id()
{
    m_Device_license_idIsSet = false;
}
utility::string_t DeviceHeartbeatDto::getCustomerName() const
{
    return m_Customer_name.get();
}


void DeviceHeartbeatDto::setCustomerName(const utility::string_t& value)
{
    m_Customer_name = value;
}

bool DeviceHeartbeatDto::customerNameIsSet() const
{
    return m_Customer_name.has_value();
}

void DeviceHeartbeatDto::unsetCustomer_name()
{
    m_Customer_name.reset();
}
utility::string_t DeviceHeartbeatDto::getHeartbeatTypeId() const
{
    return m_Heartbeat_type_id.get();
}


void DeviceHeartbeatDto::setHeartbeatTypeId(const utility::string_t& value)
{
    m_Heartbeat_type_id = value;
}

bool DeviceHeartbeatDto::heartbeatTypeIdIsSet() const
{
    return m_Heartbeat_type_id.has_value();
}

void DeviceHeartbeatDto::unsetHeartbeat_type_id()
{
    m_Heartbeat_type_id.reset();
}
std::shared_ptr<HeartbeatTypeDto> DeviceHeartbeatDto::getHeartbeatType() const
{
    return m_Heartbeat_type;
}


void DeviceHeartbeatDto::setHeartbeatType(const std::shared_ptr<HeartbeatTypeDto>& value)
{
    m_Heartbeat_type = value;
    m_Heartbeat_typeIsSet = true;
}

bool DeviceHeartbeatDto::heartbeatTypeIsSet() const
{
    return m_Heartbeat_typeIsSet;
}

void DeviceHeartbeatDto::unsetHeartbeat_type()
{
    m_Heartbeat_typeIsSet = false;
}
utility::string_t DeviceHeartbeatDto::getUserId() const
{
    return m_User_id.get();
}


void DeviceHeartbeatDto::setUserId(const utility::string_t& value)
{
    m_User_id = value;
}

bool DeviceHeartbeatDto::userIdIsSet() const
{
    return m_User_id.has_value();
}

void DeviceHeartbeatDto::unsetUser_id()
{
    m_User_id.reset();
}
std::shared_ptr<LicenseUserDto> DeviceHeartbeatDto::getLicenseUser() const
{
    return m_License_user;
}


void DeviceHeartbeatDto::setLicenseUser(const std::shared_ptr<LicenseUserDto>& value)
{
    m_License_user = value;
    m_License_userIsSet = true;
}

bool DeviceHeartbeatDto::licenseUserIsSet() const
{
    return m_License_userIsSet;
}

void DeviceHeartbeatDto::unsetLicense_user()
{
    m_License_userIsSet = false;
}
utility::string_t DeviceHeartbeatDto::getGroupId() const
{
    return m_Group_id.get();
}


void DeviceHeartbeatDto::setGroupId(const utility::string_t& value)
{
    m_Group_id = value;
}

bool DeviceHeartbeatDto::groupIdIsSet() const
{
    return m_Group_id.has_value();
}

void DeviceHeartbeatDto::unsetGroup_id()
{
    m_Group_id.reset();
}
int32_t DeviceHeartbeatDto::getValue() const
{
    return m_Value;
}

void DeviceHeartbeatDto::setValue(int32_t value)
{
    m_Value = value;
    m_ValueIsSet = true;
}

bool DeviceHeartbeatDto::valueIsSet() const
{
    return m_ValueIsSet;
}

void DeviceHeartbeatDto::unsetValue()
{
    m_ValueIsSet = false;
}

}
}
}
}


