/**
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "SlasconeOpenApiClient/model/ResourceDto.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

ResourceDto::ResourceDto()
{
}

ResourceDto::~ResourceDto()
{
}

void ResourceDto::validate()
{
    // TODO: implement validation
}

web::json::value ResourceDto::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Uri.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("uri"))] = ModelBase::toJson(m_Uri.get());
    }
    if(m_Name.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name.get());
    }

    return val;
}

bool ResourceDto::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("uri"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("uri")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUri;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUri);
            setUri(refVal_setUri);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    return ok;
}

void ResourceDto::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Uri.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("uri")), m_Uri.get()));
    }
    if(m_Name.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name.get()));
    }
}

bool ResourceDto::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("uri"))))
    {
        utility::string_t refVal_setUri;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("uri"))), refVal_setUri );
        setUri(refVal_setUri);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    return ok;
}


utility::string_t ResourceDto::getUri() const
{
    return m_Uri.get();
}


void ResourceDto::setUri(const utility::string_t& value)
{
    m_Uri = value;
}

bool ResourceDto::uriIsSet() const
{
    return m_Uri.has_value();
}

void ResourceDto::unsetUri()
{
    m_Uri.reset();
}
utility::string_t ResourceDto::getName() const
{
    return m_Name.get();
}


void ResourceDto::setName(const utility::string_t& value)
{
    m_Name = value;
}

bool ResourceDto::nameIsSet() const
{
    return m_Name.has_value();
}

void ResourceDto::unsetName()
{
    m_Name.reset();
}

}
}
}
}


