/**
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "SlasconeOpenApiClient/model/SoftwareShipmentPropertyDto.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

SoftwareShipmentPropertyDto::SoftwareShipmentPropertyDto()
{
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_Software_shipment_id = utility::conversions::to_string_t("");
    m_Software_shipment_idIsSet = false;
    m_Product_software_shipment_property_id = utility::conversions::to_string_t("");
    m_Product_software_shipment_property_idIsSet = false;
}

SoftwareShipmentPropertyDto::~SoftwareShipmentPropertyDto()
{
}

void SoftwareShipmentPropertyDto::validate()
{
    // TODO: implement validation
}

web::json::value SoftwareShipmentPropertyDto::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_Value.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("value"))] = ModelBase::toJson(m_Value.get());
    }
    if(m_Software_shipment_idIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("software_shipment_id"))] = ModelBase::toJson(m_Software_shipment_id);
    }
    if(m_Product_software_shipment_property_idIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("product_software_shipment_property_id"))] = ModelBase::toJson(m_Product_software_shipment_property_id);
    }
    if(m_Product_software_shipment_property_name.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("product_software_shipment_property_name"))] = ModelBase::toJson(m_Product_software_shipment_property_name.get());
    }
    if(m_Created_date_utc.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("created_date_utc"))] = ModelBase::toJson(m_Created_date_utc.get());
    }
    if(m_Modified_date_utc.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("modified_date_utc"))] = ModelBase::toJson(m_Modified_date_utc.get());
    }
    if(m_Last_modified_by.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("last_modified_by"))] = ModelBase::toJson(m_Last_modified_by.get());
    }

    return val;
}

bool SoftwareShipmentPropertyDto::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("value"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("value")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setValue;
            ok &= ModelBase::fromJson(fieldValue, refVal_setValue);
            setValue(refVal_setValue);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("software_shipment_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("software_shipment_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSoftwareShipmentId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSoftwareShipmentId);
            setSoftwareShipmentId(refVal_setSoftwareShipmentId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("product_software_shipment_property_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("product_software_shipment_property_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setProductSoftwareShipmentPropertyId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProductSoftwareShipmentPropertyId);
            setProductSoftwareShipmentPropertyId(refVal_setProductSoftwareShipmentPropertyId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("product_software_shipment_property_name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("product_software_shipment_property_name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setProductSoftwareShipmentPropertyName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProductSoftwareShipmentPropertyName);
            setProductSoftwareShipmentPropertyName(refVal_setProductSoftwareShipmentPropertyName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("created_date_utc"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("created_date_utc")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setCreatedDateUtc;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedDateUtc);
            setCreatedDateUtc(refVal_setCreatedDateUtc);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("modified_date_utc"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("modified_date_utc")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setModifiedDateUtc;
            ok &= ModelBase::fromJson(fieldValue, refVal_setModifiedDateUtc);
            setModifiedDateUtc(refVal_setModifiedDateUtc);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("last_modified_by"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("last_modified_by")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLastModifiedBy;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLastModifiedBy);
            setLastModifiedBy(refVal_setLastModifiedBy);
            
        }
    }
    return ok;
}

void SoftwareShipmentPropertyDto::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_Value.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("value")), m_Value.get()));
    }
    if(m_Software_shipment_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("software_shipment_id")), m_Software_shipment_id));
    }
    if(m_Product_software_shipment_property_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("product_software_shipment_property_id")), m_Product_software_shipment_property_id));
    }
    if(m_Product_software_shipment_property_name.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("product_software_shipment_property_name")), m_Product_software_shipment_property_name.get()));
    }
    if(m_Created_date_utc.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("created_date_utc")), m_Created_date_utc.get()));
    }
    if(m_Modified_date_utc.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("modified_date_utc")), m_Modified_date_utc.get()));
    }
    if(m_Last_modified_by.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("last_modified_by")), m_Last_modified_by.get()));
    }
}

bool SoftwareShipmentPropertyDto::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("value"))))
    {
        utility::string_t refVal_setValue;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("value"))), refVal_setValue );
        setValue(refVal_setValue);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("software_shipment_id"))))
    {
        utility::string_t refVal_setSoftwareShipmentId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("software_shipment_id"))), refVal_setSoftwareShipmentId );
        setSoftwareShipmentId(refVal_setSoftwareShipmentId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("product_software_shipment_property_id"))))
    {
        utility::string_t refVal_setProductSoftwareShipmentPropertyId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("product_software_shipment_property_id"))), refVal_setProductSoftwareShipmentPropertyId );
        setProductSoftwareShipmentPropertyId(refVal_setProductSoftwareShipmentPropertyId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("product_software_shipment_property_name"))))
    {
        utility::string_t refVal_setProductSoftwareShipmentPropertyName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("product_software_shipment_property_name"))), refVal_setProductSoftwareShipmentPropertyName );
        setProductSoftwareShipmentPropertyName(refVal_setProductSoftwareShipmentPropertyName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("created_date_utc"))))
    {
        utility::datetime refVal_setCreatedDateUtc;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("created_date_utc"))), refVal_setCreatedDateUtc );
        setCreatedDateUtc(refVal_setCreatedDateUtc);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("modified_date_utc"))))
    {
        utility::datetime refVal_setModifiedDateUtc;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("modified_date_utc"))), refVal_setModifiedDateUtc );
        setModifiedDateUtc(refVal_setModifiedDateUtc);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("last_modified_by"))))
    {
        utility::string_t refVal_setLastModifiedBy;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("last_modified_by"))), refVal_setLastModifiedBy );
        setLastModifiedBy(refVal_setLastModifiedBy);
    }
    return ok;
}


utility::string_t SoftwareShipmentPropertyDto::getId() const
{
    return m_Id;
}


void SoftwareShipmentPropertyDto::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool SoftwareShipmentPropertyDto::idIsSet() const
{
    return m_IdIsSet;
}

void SoftwareShipmentPropertyDto::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t SoftwareShipmentPropertyDto::getValue() const
{
    return m_Value.get();
}


void SoftwareShipmentPropertyDto::setValue(const utility::string_t& value)
{
    m_Value = value;
}

bool SoftwareShipmentPropertyDto::valueIsSet() const
{
    return m_Value.has_value();
}

void SoftwareShipmentPropertyDto::unsetValue()
{
    m_Value.reset();
}
utility::string_t SoftwareShipmentPropertyDto::getSoftwareShipmentId() const
{
    return m_Software_shipment_id;
}


void SoftwareShipmentPropertyDto::setSoftwareShipmentId(const utility::string_t& value)
{
    m_Software_shipment_id = value;
    m_Software_shipment_idIsSet = true;
}

bool SoftwareShipmentPropertyDto::softwareShipmentIdIsSet() const
{
    return m_Software_shipment_idIsSet;
}

void SoftwareShipmentPropertyDto::unsetSoftware_shipment_id()
{
    m_Software_shipment_idIsSet = false;
}
utility::string_t SoftwareShipmentPropertyDto::getProductSoftwareShipmentPropertyId() const
{
    return m_Product_software_shipment_property_id;
}


void SoftwareShipmentPropertyDto::setProductSoftwareShipmentPropertyId(const utility::string_t& value)
{
    m_Product_software_shipment_property_id = value;
    m_Product_software_shipment_property_idIsSet = true;
}

bool SoftwareShipmentPropertyDto::productSoftwareShipmentPropertyIdIsSet() const
{
    return m_Product_software_shipment_property_idIsSet;
}

void SoftwareShipmentPropertyDto::unsetProduct_software_shipment_property_id()
{
    m_Product_software_shipment_property_idIsSet = false;
}
utility::string_t SoftwareShipmentPropertyDto::getProductSoftwareShipmentPropertyName() const
{
    return m_Product_software_shipment_property_name.get();
}


void SoftwareShipmentPropertyDto::setProductSoftwareShipmentPropertyName(const utility::string_t& value)
{
    m_Product_software_shipment_property_name = value;
}

bool SoftwareShipmentPropertyDto::productSoftwareShipmentPropertyNameIsSet() const
{
    return m_Product_software_shipment_property_name.has_value();
}

void SoftwareShipmentPropertyDto::unsetProduct_software_shipment_property_name()
{
    m_Product_software_shipment_property_name.reset();
}
utility::datetime SoftwareShipmentPropertyDto::getCreatedDateUtc() const
{
    return m_Created_date_utc.get();
}


void SoftwareShipmentPropertyDto::setCreatedDateUtc(const utility::datetime& value)
{
    m_Created_date_utc = value;
}

bool SoftwareShipmentPropertyDto::createdDateUtcIsSet() const
{
    return m_Created_date_utc.has_value();
}

void SoftwareShipmentPropertyDto::unsetCreated_date_utc()
{
    m_Created_date_utc.reset();
}
utility::datetime SoftwareShipmentPropertyDto::getModifiedDateUtc() const
{
    return m_Modified_date_utc.get();
}


void SoftwareShipmentPropertyDto::setModifiedDateUtc(const utility::datetime& value)
{
    m_Modified_date_utc = value;
}

bool SoftwareShipmentPropertyDto::modifiedDateUtcIsSet() const
{
    return m_Modified_date_utc.has_value();
}

void SoftwareShipmentPropertyDto::unsetModified_date_utc()
{
    m_Modified_date_utc.reset();
}
utility::string_t SoftwareShipmentPropertyDto::getLastModifiedBy() const
{
    return m_Last_modified_by.get();
}


void SoftwareShipmentPropertyDto::setLastModifiedBy(const utility::string_t& value)
{
    m_Last_modified_by = value;
}

bool SoftwareShipmentPropertyDto::lastModifiedByIsSet() const
{
    return m_Last_modified_by.has_value();
}

void SoftwareShipmentPropertyDto::unsetLast_modified_by()
{
    m_Last_modified_by.reset();
}

}
}
}
}


