/**
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "SlasconeOpenApiClient/model/SoftwareReleaseLimitationDto.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

SoftwareReleaseLimitationDto::SoftwareReleaseLimitationDto()
{
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_Product_id = utility::conversions::to_string_t("");
    m_Product_idIsSet = false;
}

SoftwareReleaseLimitationDto::~SoftwareReleaseLimitationDto()
{
}

void SoftwareReleaseLimitationDto::validate()
{
    // TODO: implement validation
}

web::json::value SoftwareReleaseLimitationDto::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_Product_idIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("product_id"))] = ModelBase::toJson(m_Product_id);
    }
    if(m_Software_release.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("software_release"))] = ModelBase::toJson(m_Software_release.get());
    }
    if(m_Description.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("description"))] = ModelBase::toJson(m_Description.get());
    }
    if(m_Software_shipments.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("software_shipments"))] = ModelBase::toJson(m_Software_shipments.get());
    }
    if(m_Created_date_utc.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("created_date_utc"))] = ModelBase::toJson(m_Created_date_utc.get());
    }
    if(m_Modified_date_utc.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("modified_date_utc"))] = ModelBase::toJson(m_Modified_date_utc.get());
    }
    if(m_Last_modified_by.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("last_modified_by"))] = ModelBase::toJson(m_Last_modified_by.get());
    }

    return val;
}

bool SoftwareReleaseLimitationDto::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("product_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("product_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setProductId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProductId);
            setProductId(refVal_setProductId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("software_release"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("software_release")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSoftwareRelease;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSoftwareRelease);
            setSoftwareRelease(refVal_setSoftwareRelease);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("description")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDescription;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDescription);
            setDescription(refVal_setDescription);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("software_shipments"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("software_shipments")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<SoftwareShipmentDto>> refVal_setSoftwareShipments;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSoftwareShipments);
            setSoftwareShipments(refVal_setSoftwareShipments);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("created_date_utc"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("created_date_utc")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setCreatedDateUtc;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedDateUtc);
            setCreatedDateUtc(refVal_setCreatedDateUtc);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("modified_date_utc"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("modified_date_utc")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setModifiedDateUtc;
            ok &= ModelBase::fromJson(fieldValue, refVal_setModifiedDateUtc);
            setModifiedDateUtc(refVal_setModifiedDateUtc);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("last_modified_by"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("last_modified_by")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLastModifiedBy;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLastModifiedBy);
            setLastModifiedBy(refVal_setLastModifiedBy);
            
        }
    }
    return ok;
}

void SoftwareReleaseLimitationDto::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_Product_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("product_id")), m_Product_id));
    }
    if(m_Software_release.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("software_release")), m_Software_release.get()));
    }
    if(m_Description.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("description")), m_Description.get()));
    }
    if(m_Software_shipments.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("software_shipments")), m_Software_shipments.get()));
    }
    if(m_Created_date_utc.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("created_date_utc")), m_Created_date_utc.get()));
    }
    if(m_Modified_date_utc.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("modified_date_utc")), m_Modified_date_utc.get()));
    }
    if(m_Last_modified_by.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("last_modified_by")), m_Last_modified_by.get()));
    }
}

bool SoftwareReleaseLimitationDto::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("product_id"))))
    {
        utility::string_t refVal_setProductId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("product_id"))), refVal_setProductId );
        setProductId(refVal_setProductId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("software_release"))))
    {
        utility::string_t refVal_setSoftwareRelease;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("software_release"))), refVal_setSoftwareRelease );
        setSoftwareRelease(refVal_setSoftwareRelease);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        utility::string_t refVal_setDescription;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("description"))), refVal_setDescription );
        setDescription(refVal_setDescription);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("software_shipments"))))
    {
        std::vector<std::shared_ptr<SoftwareShipmentDto>> refVal_setSoftwareShipments;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("software_shipments"))), refVal_setSoftwareShipments );
        setSoftwareShipments(refVal_setSoftwareShipments);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("created_date_utc"))))
    {
        utility::datetime refVal_setCreatedDateUtc;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("created_date_utc"))), refVal_setCreatedDateUtc );
        setCreatedDateUtc(refVal_setCreatedDateUtc);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("modified_date_utc"))))
    {
        utility::datetime refVal_setModifiedDateUtc;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("modified_date_utc"))), refVal_setModifiedDateUtc );
        setModifiedDateUtc(refVal_setModifiedDateUtc);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("last_modified_by"))))
    {
        utility::string_t refVal_setLastModifiedBy;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("last_modified_by"))), refVal_setLastModifiedBy );
        setLastModifiedBy(refVal_setLastModifiedBy);
    }
    return ok;
}


utility::string_t SoftwareReleaseLimitationDto::getId() const
{
    return m_Id;
}


void SoftwareReleaseLimitationDto::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool SoftwareReleaseLimitationDto::idIsSet() const
{
    return m_IdIsSet;
}

void SoftwareReleaseLimitationDto::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t SoftwareReleaseLimitationDto::getProductId() const
{
    return m_Product_id;
}


void SoftwareReleaseLimitationDto::setProductId(const utility::string_t& value)
{
    m_Product_id = value;
    m_Product_idIsSet = true;
}

bool SoftwareReleaseLimitationDto::productIdIsSet() const
{
    return m_Product_idIsSet;
}

void SoftwareReleaseLimitationDto::unsetProduct_id()
{
    m_Product_idIsSet = false;
}
utility::string_t SoftwareReleaseLimitationDto::getSoftwareRelease() const
{
    return m_Software_release.get();
}


void SoftwareReleaseLimitationDto::setSoftwareRelease(const utility::string_t& value)
{
    m_Software_release = value;
}

bool SoftwareReleaseLimitationDto::softwareReleaseIsSet() const
{
    return m_Software_release.has_value();
}

void SoftwareReleaseLimitationDto::unsetSoftware_release()
{
    m_Software_release.reset();
}
utility::string_t SoftwareReleaseLimitationDto::getDescription() const
{
    return m_Description.get();
}


void SoftwareReleaseLimitationDto::setDescription(const utility::string_t& value)
{
    m_Description = value;
}

bool SoftwareReleaseLimitationDto::descriptionIsSet() const
{
    return m_Description.has_value();
}

void SoftwareReleaseLimitationDto::unsetDescription()
{
    m_Description.reset();
}
std::vector<std::shared_ptr<SoftwareShipmentDto>> SoftwareReleaseLimitationDto::getSoftwareShipments() const
{
    return m_Software_shipments.get();
}


void SoftwareReleaseLimitationDto::setSoftwareShipments(const std::vector<std::shared_ptr<SoftwareShipmentDto>>& value)
{
    m_Software_shipments = value;
}

bool SoftwareReleaseLimitationDto::softwareShipmentsIsSet() const
{
    return m_Software_shipments.has_value();
}

void SoftwareReleaseLimitationDto::unsetSoftware_shipments()
{
    m_Software_shipments.reset();
}
utility::datetime SoftwareReleaseLimitationDto::getCreatedDateUtc() const
{
    return m_Created_date_utc.get();
}


void SoftwareReleaseLimitationDto::setCreatedDateUtc(const utility::datetime& value)
{
    m_Created_date_utc = value;
}

bool SoftwareReleaseLimitationDto::createdDateUtcIsSet() const
{
    return m_Created_date_utc.has_value();
}

void SoftwareReleaseLimitationDto::unsetCreated_date_utc()
{
    m_Created_date_utc.reset();
}
utility::datetime SoftwareReleaseLimitationDto::getModifiedDateUtc() const
{
    return m_Modified_date_utc.get();
}


void SoftwareReleaseLimitationDto::setModifiedDateUtc(const utility::datetime& value)
{
    m_Modified_date_utc = value;
}

bool SoftwareReleaseLimitationDto::modifiedDateUtcIsSet() const
{
    return m_Modified_date_utc.has_value();
}

void SoftwareReleaseLimitationDto::unsetModified_date_utc()
{
    m_Modified_date_utc.reset();
}
utility::string_t SoftwareReleaseLimitationDto::getLastModifiedBy() const
{
    return m_Last_modified_by.get();
}


void SoftwareReleaseLimitationDto::setLastModifiedBy(const utility::string_t& value)
{
    m_Last_modified_by = value;
}

bool SoftwareReleaseLimitationDto::lastModifiedByIsSet() const
{
    return m_Last_modified_by.has_value();
}

void SoftwareReleaseLimitationDto::unsetLast_modified_by()
{
    m_Last_modified_by.reset();
}

}
}
}
}


