/**
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "SlasconeOpenApiClient/model/UsageHeartbeatResponseErrors.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

UsageHeartbeatResponseErrors::UsageHeartbeatResponseErrors()
{
    m_Id = 0;
    m_IdIsSet = false;
}

UsageHeartbeatResponseErrors::~UsageHeartbeatResponseErrors()
{
}

void UsageHeartbeatResponseErrors::validate()
{
    // TODO: implement validation
}

web::json::value UsageHeartbeatResponseErrors::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_Message.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("message"))] = ModelBase::toJson(m_Message.get());
    }
    if(m_Help.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("help"))] = ModelBase::toJson(m_Help.get());
    }
    if(m_ExpectedErrors.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("expectedErrors"))] = ModelBase::toJson(m_ExpectedErrors.get());
    }

    return val;
}

bool UsageHeartbeatResponseErrors::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("message"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("message")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMessage;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMessage);
            setMessage(refVal_setMessage);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("help"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("help")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setHelp;
            ok &= ModelBase::fromJson(fieldValue, refVal_setHelp);
            setHelp(refVal_setHelp);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("expectedErrors"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("expectedErrors")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<ErrorResultObjects>> refVal_setExpectedErrors;
            ok &= ModelBase::fromJson(fieldValue, refVal_setExpectedErrors);
            setExpectedErrors(refVal_setExpectedErrors);
            
        }
    }
    return ok;
}

void UsageHeartbeatResponseErrors::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_Message.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("message")), m_Message.get()));
    }
    if(m_Help.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("help")), m_Help.get()));
    }
    if(m_ExpectedErrors.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("expectedErrors")), m_ExpectedErrors.get()));
    }
}

bool UsageHeartbeatResponseErrors::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        int32_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("message"))))
    {
        utility::string_t refVal_setMessage;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("message"))), refVal_setMessage );
        setMessage(refVal_setMessage);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("help"))))
    {
        utility::string_t refVal_setHelp;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("help"))), refVal_setHelp );
        setHelp(refVal_setHelp);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("expectedErrors"))))
    {
        std::vector<std::shared_ptr<ErrorResultObjects>> refVal_setExpectedErrors;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("expectedErrors"))), refVal_setExpectedErrors );
        setExpectedErrors(refVal_setExpectedErrors);
    }
    return ok;
}


int32_t UsageHeartbeatResponseErrors::getId() const
{
    return m_Id;
}

void UsageHeartbeatResponseErrors::setId(int32_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool UsageHeartbeatResponseErrors::idIsSet() const
{
    return m_IdIsSet;
}

void UsageHeartbeatResponseErrors::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t UsageHeartbeatResponseErrors::getMessage() const
{
    return m_Message.get();
}


void UsageHeartbeatResponseErrors::setMessage(const utility::string_t& value)
{
    m_Message = value;
}

bool UsageHeartbeatResponseErrors::messageIsSet() const
{
    return m_Message.has_value();
}

void UsageHeartbeatResponseErrors::unsetMessage()
{
    m_Message.reset();
}
utility::string_t UsageHeartbeatResponseErrors::getHelp() const
{
    return m_Help.get();
}


void UsageHeartbeatResponseErrors::setHelp(const utility::string_t& value)
{
    m_Help = value;
}

bool UsageHeartbeatResponseErrors::helpIsSet() const
{
    return m_Help.has_value();
}

void UsageHeartbeatResponseErrors::unsetHelp()
{
    m_Help.reset();
}
std::vector<std::shared_ptr<ErrorResultObjects>> UsageHeartbeatResponseErrors::getExpectedErrors() const
{
    return m_ExpectedErrors.get();
}


void UsageHeartbeatResponseErrors::setExpectedErrors(const std::vector<std::shared_ptr<ErrorResultObjects>>& value)
{
    m_ExpectedErrors = value;
}

bool UsageHeartbeatResponseErrors::expectedErrorsIsSet() const
{
    return m_ExpectedErrors.has_value();
}

void UsageHeartbeatResponseErrors::unsetExpectedErrors()
{
    m_ExpectedErrors.reset();
}

}
}
}
}


