/**
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AddHeartbeatDto.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_AddHeartbeatDto_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_AddHeartbeatDto_H_


#include "SlasconeOpenApiClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// 
/// </summary>
class  AddHeartbeatDto
    : public ModelBase
{
public:
    AddHeartbeatDto();
    virtual ~AddHeartbeatDto();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// AddHeartbeatDto members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getProductId() const;
    bool productIdIsSet() const;
    void unsetProduct_id();

    void setProductId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getClientId() const;
    bool clientIdIsSet() const;
    void unsetClient_id();

    void setClientId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getSoftwareVersion() const;
    bool softwareVersionIsSet() const;
    void unsetSoftware_version();

    void setSoftwareVersion(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getOperatingSystem() const;
    bool operatingSystemIsSet() const;
    void unsetOperating_system();

    void setOperatingSystem(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getTokenKey() const;
    bool tokenKeyIsSet() const;
    void unsetToken_key();

    void setTokenKey(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getGroupId() const;
    bool groupIdIsSet() const;
    void unsetGroup_id();

    void setGroupId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getHeartbeatTypeId() const;
    bool heartbeatTypeIdIsSet() const;
    void unsetHeartbeat_type_id();

    void setHeartbeatTypeId(const utility::string_t& value);


protected:
    utility::string_t m_Product_id;
    bool m_Product_idIsSet;
    utility::string_t m_Client_id;
    bool m_Client_idIsSet;
    utility::string_t m_Software_version;
    bool m_Software_versionIsSet;
    utility::string_t m_Operating_system;
    bool m_Operating_systemIsSet;
    utility::string_t m_Token_key;
    bool m_Token_keyIsSet;
    utility::string_t m_Group_id;
    bool m_Group_idIsSet;
    utility::string_t m_Heartbeat_type_id;
    bool m_Heartbeat_type_idIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_AddHeartbeatDto_H_ */
