/**
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SoftwareShipmentPropertyDto.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_SoftwareShipmentPropertyDto_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_SoftwareShipmentPropertyDto_H_


#include "SlasconeOpenApiClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  SoftwareShipmentPropertyDto
    : public ModelBase
{
public:
    SoftwareShipmentPropertyDto();
    virtual ~SoftwareShipmentPropertyDto();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// SoftwareShipmentPropertyDto members


    utility::string_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(const utility::string_t& value);

    utility::string_t getValue() const;
    bool valueIsSet() const;
    void unsetValue();
    void setValue(const utility::string_t& value);

    utility::string_t getSoftwareShipmentId() const;
    bool softwareShipmentIdIsSet() const;
    void unsetSoftware_shipment_id();
    void setSoftwareShipmentId(const utility::string_t& value);

    utility::string_t getProductSoftwareShipmentPropertyId() const;
    bool productSoftwareShipmentPropertyIdIsSet() const;
    void unsetProduct_software_shipment_property_id();
    void setProductSoftwareShipmentPropertyId(const utility::string_t& value);

    utility::string_t getProductSoftwareShipmentPropertyName() const;
    bool productSoftwareShipmentPropertyNameIsSet() const;
    void unsetProduct_software_shipment_property_name();
    void setProductSoftwareShipmentPropertyName(const utility::string_t& value);

    utility::datetime getCreatedDateUtc() const;
    bool createdDateUtcIsSet() const;
    void unsetCreated_date_utc();
    void setCreatedDateUtc(const utility::datetime& value);

    utility::datetime getModifiedDateUtc() const;
    bool modifiedDateUtcIsSet() const;
    void unsetModified_date_utc();
    void setModifiedDateUtc(const utility::datetime& value);

    utility::string_t getLastModifiedBy() const;
    bool lastModifiedByIsSet() const;
    void unsetLast_modified_by();
    void setLastModifiedBy(const utility::string_t& value);


protected:
    utility::string_t m_Id;
    bool m_IdIsSet;

    utility::string_t m_Value;
    bool m_ValueIsSet;

    utility::string_t m_Software_shipment_id;
    bool m_Software_shipment_idIsSet;

    utility::string_t m_Product_software_shipment_property_id;
    bool m_Product_software_shipment_property_idIsSet;

    utility::string_t m_Product_software_shipment_property_name;
    bool m_Product_software_shipment_property_nameIsSet;

    utility::datetime m_Created_date_utc;
    bool m_Created_date_utcIsSet;

    utility::datetime m_Modified_date_utc;
    bool m_Modified_date_utcIsSet;

    utility::string_t m_Last_modified_by;
    bool m_Last_modified_byIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_SoftwareShipmentPropertyDto_H_ */
