/**
 * SLASCONE API
 * Please visit our official [Documentation](https://support.slascone.com/hc/en-us/sections/360004685737-API) and/or our [GitHub repository](https://github.com/slascone/) and/or our [NuGet package](https://www.nuget.org/packages/Slascone.Client/). Always use Version 2 of this API (Version 1.3 is deprecated).
 *
 * The version of the OpenAPI document: v2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.11.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * TemplateLimitationDto.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_TemplateLimitationDto_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_TemplateLimitationDto_H_


#include "SlasconeOpenApiClient/ModelBase.h"

#include "SlasconeOpenApiClient/model/ConsumptionBalanceMode.h"
#include "SlasconeOpenApiClient/model/ConsumptionResetPeriod.h"
#include <cpprest/details/basic_types.h>
#include "SlasconeOpenApiClient/model/TemplateLimitationAlertDto.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class TemplateLimitationAlertDto;


/// <summary>
/// 
/// </summary>
class  TemplateLimitationDto
    : public ModelBase
{
public:
    TemplateLimitationDto();
    virtual ~TemplateLimitationDto();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// TemplateLimitationDto members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getTemplateId() const;
    bool templateIdIsSet() const;
    void unsetTemplate_id();

    void setTemplateId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getLimitationId() const;
    bool limitationIdIsSet() const;
    void unsetLimitation_id();

    void setLimitationId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getLimitationName() const;
    bool limitationNameIsSet() const;
    void unsetLimitation_name();

    void setLimitationName(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    bool isIsAdjustable() const;
    bool isAdjustableIsSet() const;
    void unsetIs_adjustable();

    void setIsAdjustable(bool value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getLimit() const;
    bool limitIsSet() const;
    void unsetLimit();

    void setLimit(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<ConsumptionResetPeriod> getConsumptionResetMode() const;
    bool consumptionResetModeIsSet() const;
    void unsetConsumption_reset_mode();

    void setConsumptionResetMode(const std::shared_ptr<ConsumptionResetPeriod>& value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getConsumptionResetPeriodDays() const;
    bool consumptionResetPeriodDaysIsSet() const;
    void unsetConsumption_reset_period_days();

    void setConsumptionResetPeriodDays(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    double getGoodwill() const;
    bool goodwillIsSet() const;
    void unsetGoodwill();

    void setGoodwill(double value);

    /// <summary>
    /// 
    /// </summary>
    bool isEnforceLimit() const;
    bool enforceLimitIsSet() const;
    void unsetEnforce_limit();

    void setEnforceLimit(bool value);

    /// <summary>
    /// 
    /// </summary>
    bool isUserProvisioning() const;
    bool userProvisioningIsSet() const;
    void unsetUser_provisioning();

    void setUserProvisioning(bool value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<ConsumptionBalanceMode> getConsumptionBalanceMode() const;
    bool consumptionBalanceModeIsSet() const;
    void unsetConsumption_balance_mode();

    void setConsumptionBalanceMode(const std::shared_ptr<ConsumptionBalanceMode>& value);

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<TemplateLimitationAlertDto>>& getAlerts();
    bool alertsIsSet() const;
    void unsetAlerts();

    void setAlerts(const std::vector<std::shared_ptr<TemplateLimitationAlertDto>>& value);


protected:
    utility::string_t m_Template_id;
    bool m_Template_idIsSet;
    utility::string_t m_Limitation_id;
    bool m_Limitation_idIsSet;
    utility::string_t m_Limitation_name;
    bool m_Limitation_nameIsSet;
    bool m_Is_adjustable;
    bool m_Is_adjustableIsSet;
    int32_t m_Limit;
    bool m_LimitIsSet;
    std::shared_ptr<ConsumptionResetPeriod> m_Consumption_reset_mode;
    bool m_Consumption_reset_modeIsSet;
    int32_t m_Consumption_reset_period_days;
    bool m_Consumption_reset_period_daysIsSet;
    double m_Goodwill;
    bool m_GoodwillIsSet;
    bool m_Enforce_limit;
    bool m_Enforce_limitIsSet;
    bool m_User_provisioning;
    bool m_User_provisioningIsSet;
    std::shared_ptr<ConsumptionBalanceMode> m_Consumption_balance_mode;
    bool m_Consumption_balance_modeIsSet;
    std::vector<std::shared_ptr<TemplateLimitationAlertDto>> m_Alerts;
    bool m_AlertsIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_TemplateLimitationDto_H_ */
